const LEGACY_MARKET_CODE_MAP = {
  'thai-government': 'thai_government',
  baac: 'baac',
  gsb: 'gsb',
  'gsb-1year-100': 'gsb',
  lao: 'tlzc',
  'lao-redcross': 'lao_redcross',
  'lao-pathana': 'lao_pathana',
  'lao-tv': 'lao_tv',
  'lao-hd': 'lao_hd',
  'lao-extra': 'lao_extra',
  'lao-star': 'lao_star',
  'lao-stars': 'lao_star',
  'lao-star-vip': 'lao_star_vip',
  'lao-stars-vip': 'lao_star_vip',
  'lao-union': 'lao_union',
  'lao-union-vip': 'lao_union_vip',
  laounionvip: 'lao_union_vip',
  'lao-asean': 'lao_asean',
  laoasean: 'lao_asean',
  'hanoi-extra': 'hanoi_extra',
  hanoiextra: 'hanoi_extra',
  'hanoi-star': 'hanoi_star',
  hanoistar: 'hanoi_star',
  'hanoi-develop': 'hanoi_develop',
  hanoidevelop: 'hanoi_develop',
  'hanoi-hd': 'hanoi_hd',
  hanoihd: 'hanoi_hd',
  'hanoi-tv': 'hanoi_tv',
  hanoitv: 'hanoi_tv',
  'hanoi-redcross': 'hanoi_redcross',
  hanoiredcross: 'hanoi_redcross',
  'hanoi-union': 'hanoi_union',
  hanoiunion: 'hanoi_union',
  'hanoi-asean': 'hanoi_asean',
  hanoiasean: 'hanoi_asean',
  'hanoi-special': 'hanoi_special',
  'lao-vip': 'lao_vip',
  'dowjones-vip': 'dowjones_vip',
  'stock-nikkei-morning': 'nikkei_morning',
  'stock-nikkei-morning-vip': 'nikkei_morning_vip',
  'nikkei-morning-vip': 'nikkei_morning_vip',
  'stock-hangseng-morning-vip': 'hangseng_morning_vip',
  'hangseng-morning-vip': 'hangseng_morning_vip',
  'stock-china-morning-vip': 'china_morning_vip',
  'china-morning-vip': 'china_morning_vip',
  'stock-china-afternoon': 'china_afternoon',
  'stock-china-afternoon-vip': 'china_afternoon_vip',
  'china-afternoon-vip': 'china_afternoon_vip',
  'stock-nikkei-afternoon-vip': 'nikkei_afternoon_vip',
  'nikkei-afternoon-vip': 'nikkei_afternoon_vip',
  'stock-korea-vip': 'korea_vip',
  'korea-vip': 'korea_vip',
  'stock-taiwan-vip': 'taiwan_vip',
  'taiwan-vip': 'taiwan_vip',
  'stock-hangseng-afternoon-vip': 'hangseng_afternoon_vip',
  'hangseng-afternoon-vip': 'hangseng_afternoon_vip',
  'stock-russia-vip': 'russia_vip',
  'russia-vip': 'russia_vip',
  'stock-singapore-vip': 'singapore_vip',
  'singapore-vip': 'singapore_vip',
  'stock-germany-vip': 'germany_vip',
  'germany-vip': 'germany_vip',
  'stock-england-vip': 'england_vip',
  'england-vip': 'england_vip'
};

const normalizeLotteryCode = (value) => {
  const normalized = String(value || '').trim();
  if (!normalized) return '';
  return LEGACY_MARKET_CODE_MAP[normalized] || normalized.replace(/-/g, '_');
};

module.exports = {
  LEGACY_MARKET_CODE_MAP,
  normalizeLotteryCode
};
